### ISSUE TITLE
Docker Image Restart Loop Issue

### ISSUE THREAD

**Issue by Pyrlik** [frefrik/comfyui-flux#8]
Hello, and thanks for the great setup!

I've recently noticed an issue where the Docker image gets stuck in a constant restart loop with the following message:

Updating ComfyUI...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>

I first noticed this yesterday. I'm not sure, but it seems like it might be related to a recent change in the ComfyUI repository logic:
https://github.com/comfyanonymous/ComfyUI/issues/7025

Could you check if this is indeed related?

Thanks in advance!

**Comment by sanya191** [comment]
Hi, I confirm the error, I renamed the folder with data (new deployment), the error does not start.
LOG:
`
********** ERROR ***********

comfyui-frontend-package is not installed. Please install the updated requirements.txt file by running:

/usr/local/bin/python3 -m pip install -r requirements.txt

This error is happening because the ComfyUI frontend is no longer shipped as part of the main repo but as a pip package instead.

********** ERROR **********
`

**Comment by frefrik** [comment]
I pushed a fix now, can you pull new image and try again?
`pip install -r requirements.txt` is now run on every bootup to prevent this from happening again.

**Comment by smcnaught1** [comment]
Appreciate the work you have done frefrik.  

I have re-deployed the instance, pulling the new image via Portainer.  I think the issues still exists as I am still getting the following repeating in the log files:

```
Updating ComfyUI...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
```

Unless I am still doing something wrong.  

Thanks

**Comment by FooleanBool** [comment]
Thank you frefrik,
This worked for me.
